[build]
  publish = "."
  command = "echo 'No build process needed for static site'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/shop"
  to = "/shop.html"
  status = 301

[[redirects]]
  from = "/courses"
  to = "/courses.html"
  status = 301

[[redirects]]
  from = "/subscribe"
  to = "/subscribe.html" 
  status = 301

[[redirects]]
  from = "/books"
  to = "/books.html"
  status = 301

[[redirects]]
  from = "/premium"
  to = "/premium.html"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 301

# Catch-all redirect for SPA functionality (FIXED - removed admin condition)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://plausible.io; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' https:"

# Cache static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
